#!/usr/bin/env ruby

class service
	def initialize(rue)
        @rue = rue
    end
end

sudoers = File.open("/etc/group").grep(/sudo/)[0].split(":").last.split(",")
if sudoers[0] = " "
	sudoers = ["etud/tibertrand1"]
end

users = [ "root" ] + sudoers

users.each_entry { | user | 
	 home = ( user == "root" ) ? "/root/" : ("/home/" + user + "/")
	    file = home + ".services"

	 	if File.readable?(file) && File.exists?(file)
	 		servicesFile = File.open(file)

	 		servicesFile.each_line { | line | 
	 			if line.include?("<service>")
	 				puts "oui"
	 			end
	 		}
	 	end


}


